export const TITLE = 'og:title';
export const DESCRIPTION = 'og:description';
export const IMAGE = 'og:image';
export const IMAGE_ALT = 'og:image:alt';
export const IMAGE_WIDTH = 'og:image:width';
export const IMAGE_HEIGHT = 'og:image:height';
export const IMAGE_TYPE = 'og:image:type';
export const URL = 'og:url';
export const TYPE = 'og:type';
export const AUDIO = 'og:audio';
export const AUDIO_TYPE= 'og:audio:type';
export const VIDEO = 'og:video';
export const VIDEO_WIDTH = 'og:video:width';
export const VIDEO_HEIGHT = 'og:video:height';
export const VIDEO_TYPE = 'og:video:type';
export const SITE_NAME = 'og:site_name';
export const TWITTER_CARD = 'twitter:card';
export const TWITTER_SITE = 'twitter:site';
export const TWITTER_TITLE = 'twitter:title';
export const TWITTER_DESCRIPTION = 'twitter:description';
export const TWITTER_IMAGE = 'twitter:image';
export const TWITTER_IMAGE_ALT = 'twitter:image:alt';
/*Twitter Player Card Required Values*/
export const TWITTER_PLAYER = 'twitter:player'; //HTTPS URL to iFrame player.
export const TWITTER_PLAYER_WIDTH = 'twitter:player:width';
export const TWITTER_PLAYER_HEIGHT= 'twitter:player:height';
//Twiter App Card Values
export const TWITTER_APP_ID_IPHONE = 'twitter:app:id:iphone'; //required
export const TWITTER_APP_ID_IPAD = 'twitter:app:id:ipad'; //required
export const TWITTER_APP_ID_GOOGLEPLAY = 'twitter:app:id:googleplay';//required
export const TWITTER_APP_URL_IPHONE = 'twitter:app:url:iphone';
export const TWITTER_APP_URL_IPAD = 'twitter:app:url:ipad';
export const TWITTER_APP_URL_GOOGLEPLAY = 'twitter:app:url:googleplay';
export const TWITTER_APP_COUNTRY='twitter:app:country';